<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\City;
use App\Models\State;
use App\Models\Country;

class CitySeeder extends Seeder
{
    public function run(): void
    {
        $cities = [
            // India - States with major cities
            ['name' => 'Mumbai', 'state_name' => 'Maharashtra', 'country_code' => 'IN'],
            ['name' => 'Pune', 'state_name' => 'Maharashtra', 'country_code' => 'IN'],
            ['name' => 'Nagpur', 'state_name' => 'Maharashtra', 'country_code' => 'IN'],
            ['name' => 'Thane', 'state_name' => 'Maharashtra', 'country_code' => 'IN'],
            ['name' => 'Delhi', 'state_name' => 'Delhi', 'country_code' => 'IN'],
            ['name' => 'New Delhi', 'state_name' => 'Delhi', 'country_code' => 'IN'],
            ['name' => 'Bangalore', 'state_name' => 'Karnataka', 'country_code' => 'IN'],
            ['name' => 'Mysore', 'state_name' => 'Karnataka', 'country_code' => 'IN'],
            ['name' => 'Hubli', 'state_name' => 'Karnataka', 'country_code' => 'IN'],
            ['name' => 'Chennai', 'state_name' => 'Tamil Nadu', 'country_code' => 'IN'],
            ['name' => 'Coimbatore', 'state_name' => 'Tamil Nadu', 'country_code' => 'IN'],
            ['name' => 'Madurai', 'state_name' => 'Tamil Nadu', 'country_code' => 'IN'],
            ['name' => 'Hyderabad', 'state_name' => 'Telangana', 'country_code' => 'IN'],
            ['name' => 'Warangal', 'state_name' => 'Telangana', 'country_code' => 'IN'],
            ['name' => 'Kolkata', 'state_name' => 'West Bengal', 'country_code' => 'IN'],
            ['name' => 'Howrah', 'state_name' => 'West Bengal', 'country_code' => 'IN'],
            ['name' => 'Durgapur', 'state_name' => 'West Bengal', 'country_code' => 'IN'],
            ['name' => 'Ahmedabad', 'state_name' => 'Gujarat', 'country_code' => 'IN'],
            ['name' => 'Surat', 'state_name' => 'Gujarat', 'country_code' => 'IN'],
            ['name' => 'Vadodara', 'state_name' => 'Gujarat', 'country_code' => 'IN'],
            ['name' => 'Jaipur', 'state_name' => 'Rajasthan', 'country_code' => 'IN'],
            ['name' => 'Jodhpur', 'state_name' => 'Rajasthan', 'country_code' => 'IN'],
            ['name' => 'Udaipur', 'state_name' => 'Rajasthan', 'country_code' => 'IN'],
            ['name' => 'Lucknow', 'state_name' => 'Uttar Pradesh', 'country_code' => 'IN'],
            ['name' => 'Kanpur', 'state_name' => 'Uttar Pradesh', 'country_code' => 'IN'],
            ['name' => 'Agra', 'state_name' => 'Uttar Pradesh', 'country_code' => 'IN'],
            ['name' => 'Varanasi', 'state_name' => 'Uttar Pradesh', 'country_code' => 'IN'],
            ['name' => 'Prayagraj', 'state_name' => 'Uttar Pradesh', 'country_code' => 'IN'],
            ['name' => 'Ghaziabad', 'state_name' => 'Uttar Pradesh', 'country_code' => 'IN'],
            ['name' => 'Noida', 'state_name' => 'Uttar Pradesh', 'country_code' => 'IN'],
            ['name' => 'Chandigarh', 'state_name' => 'Chandigarh', 'country_code' => 'IN'],
            ['name' => 'Ludhiana', 'state_name' => 'Punjab', 'country_code' => 'IN'],
            ['name' => 'Amritsar', 'state_name' => 'Punjab', 'country_code' => 'IN'],
            ['name' => 'Jalandhar', 'state_name' => 'Punjab', 'country_code' => 'IN'],
            ['name' => 'Patiala', 'state_name' => 'Punjab', 'country_code' => 'IN'],
            ['name' => 'Bhopal', 'state_name' => 'Madhya Pradesh', 'country_code' => 'IN'],
            ['name' => 'Indore', 'state_name' => 'Madhya Pradesh', 'country_code' => 'IN'],
            ['name' => 'Gwalior', 'state_name' => 'Madhya Pradesh', 'country_code' => 'IN'],
            ['name' => 'Patna', 'state_name' => 'Bihar', 'country_code' => 'IN'],
            ['name' => 'Gaya', 'state_name' => 'Bihar', 'country_code' => 'IN'],
            ['name' => 'Ranchi', 'state_name' => 'Jharkhand', 'country_code' => 'IN'],
            ['name' => 'Jamshedpur', 'state_name' => 'Jharkhand', 'country_code' => 'IN'],
            ['name' => 'Dhanbad', 'state_name' => 'Jharkhand', 'country_code' => 'IN'],
            ['name' => 'Bhubaneswar', 'state_name' => 'Odisha', 'country_code' => 'IN'],
            ['name' => 'Cuttack', 'state_name' => 'Odisha', 'country_code' => 'IN'],
            ['name' => 'Rourkela', 'state_name' => 'Odisha', 'country_code' => 'IN'],
            ['name' => 'Thiruvananthapuram', 'state_name' => 'Kerala', 'country_code' => 'IN'],
            ['name' => 'Kochi', 'state_name' => 'Kerala', 'country_code' => 'IN'],
            ['name' => 'Kozhikode', 'state_name' => 'Kerala', 'country_code' => 'IN'],
            ['name' => 'Thrissur', 'state_name' => 'Kerala', 'country_code' => 'IN'],
            ['name' => 'Guwahati', 'state_name' => 'Assam', 'country_code' => 'IN'],
            ['name' => 'Dispur', 'state_name' => 'Assam', 'country_code' => 'IN'],
            ['name' => 'Shillong', 'state_name' => 'Meghalaya', 'country_code' => 'IN'],
            ['name' => 'Imphal', 'state_name' => 'Manipur', 'country_code' => 'IN'],
            ['name' => 'Aizawl', 'state_name' => 'Mizoram', 'country_code' => 'IN'],
            ['name' => 'Kohima', 'state_name' => 'Nagaland', 'country_code' => 'IN'],
            ['name' => 'Agartala', 'state_name' => 'Tripura', 'country_code' => 'IN'],
            ['name' => 'Itanagar', 'state_name' => 'Arunachal Pradesh', 'country_code' => 'IN'],
            ['name' => 'Gangtok', 'state_name' => 'Sikkim', 'country_code' => 'IN'],
            ['name' => 'Panaji', 'state_name' => 'Goa', 'country_code' => 'IN'],
            ['name' => 'Vasco da Gama', 'state_name' => 'Goa', 'country_code' => 'IN'],
            ['name' => 'Dehradun', 'state_name' => 'Uttarakhand', 'country_code' => 'IN'],
            ['name' => 'Haridwar', 'state_name' => 'Uttarakhand', 'country_code' => 'IN'],
            ['name' => 'Nainital', 'state_name' => 'Uttarakhand', 'country_code' => 'IN'],
            ['name' => 'Raipur', 'state_name' => 'Chhattisgarh', 'country_code' => 'IN'],
            ['name' => 'Bilaspur', 'state_name' => 'Chhattisgarh', 'country_code' => 'IN'],
            ['name' => 'Shimla', 'state_name' => 'Himachal Pradesh', 'country_code' => 'IN'],
            ['name' => 'Manali', 'state_name' => 'Himachal Pradesh', 'country_code' => 'IN'],
            ['name' => 'Srinagar', 'state_name' => 'Jammu and Kashmir', 'country_code' => 'IN'],
            ['name' => 'Jammu', 'state_name' => 'Jammu and Kashmir', 'country_code' => 'IN'],
            ['name' => 'Leh', 'state_name' => 'Ladakh', 'country_code' => 'IN'],
            ['name' => 'Faridabad', 'state_name' => 'Haryana', 'country_code' => 'IN'],
            ['name' => 'Gurgaon', 'state_name' => 'Haryana', 'country_code' => 'IN'],
            ['name' => 'Karnal', 'state_name' => 'Haryana', 'country_code' => 'IN'],
            ['name' => 'Visakhapatnam', 'state_name' => 'Andhra Pradesh', 'country_code' => 'IN'],
            ['name' => 'Vijayawada', 'state_name' => 'Andhra Pradesh', 'country_code' => 'IN'],
            ['name' => 'Tirupati', 'state_name' => 'Andhra Pradesh', 'country_code' => 'IN'],
            ['name' => 'Guntur', 'state_name' => 'Andhra Pradesh', 'country_code' => 'IN'],
            ['name' => 'Vijayanagaram', 'state_name' => 'Andhra Pradesh', 'country_code' => 'IN'],
            ['name' => 'Puducherry', 'state_name' => 'Puducherry', 'country_code' => 'IN'],
            ['name' => 'Port Blair', 'state_name' => 'Andaman and Nicobar Islands', 'country_code' => 'IN'],

            // United States - Major cities
            ['name' => 'New York City', 'state_name' => 'New York', 'country_code' => 'US'],
            ['name' => 'Buffalo', 'state_name' => 'New York', 'country_code' => 'US'],
            ['name' => 'Rochester', 'state_name' => 'New York', 'country_code' => 'US'],
            ['name' => 'Los Angeles', 'state_name' => 'California', 'country_code' => 'US'],
            ['name' => 'San Francisco', 'state_name' => 'California', 'country_code' => 'US'],
            ['name' => 'San Diego', 'state_name' => 'California', 'country_code' => 'US'],
            ['name' => 'San Jose', 'state_name' => 'California', 'country_code' => 'US'],
            ['name' => 'Sacramento', 'state_name' => 'California', 'country_code' => 'US'],
            ['name' => 'Chicago', 'state_name' => 'Illinois', 'country_code' => 'US'],
            ['name' => 'Houston', 'state_name' => 'Texas', 'country_code' => 'US'],
            ['name' => 'Dallas', 'state_name' => 'Texas', 'country_code' => 'US'],
            ['name' => 'Austin', 'state_name' => 'Texas', 'country_code' => 'US'],
            ['name' => 'San Antonio', 'state_name' => 'Texas', 'country_code' => 'US'],
            ['name' => 'Fort Worth', 'state_name' => 'Texas', 'country_code' => 'US'],
            ['name' => 'Phoenix', 'state_name' => 'Arizona', 'country_code' => 'US'],
            ['name' => 'Philadelphia', 'state_name' => 'Pennsylvania', 'country_code' => 'US'],
            ['name' => 'Pittsburgh', 'state_name' => 'Pennsylvania', 'country_code' => 'US'],
            ['name' => 'San Antonio', 'state_name' => 'Texas', 'country_code' => 'US'],
            ['name' => 'San Diego', 'state_name' => 'California', 'country_code' => 'US'],
            ['name' => 'Dallas', 'state_name' => 'Texas', 'country_code' => 'US'],
            ['name' => 'San Jose', 'state_name' => 'California', 'country_code' => 'US'],
            ['name' => 'Austin', 'state_name' => 'Texas', 'country_code' => 'US'],
            ['name' => 'Jacksonville', 'state_name' => 'Florida', 'country_code' => 'US'],
            ['name' => 'Miami', 'state_name' => 'Florida', 'country_code' => 'US'],
            ['name' => 'Tampa', 'state_name' => 'Florida', 'country_code' => 'US'],
            ['name' => 'Orlando', 'state_name' => 'Florida', 'country_code' => 'US'],
            ['name' => 'Fort Worth', 'state_name' => 'Texas', 'country_code' => 'US'],
            ['name' => 'Columbus', 'state_name' => 'Ohio', 'country_code' => 'US'],
            ['name' => 'Charlotte', 'state_name' => 'North Carolina', 'country_code' => 'US'],
            ['name' => 'Seattle', 'state_name' => 'Washington', 'country_code' => 'US'],
            ['name' => 'Denver', 'state_name' => 'Colorado', 'country_code' => 'US'],
            ['name' => 'El Paso', 'state_name' => 'Texas', 'country_code' => 'US'],
            ['name' => 'Detroit', 'state_name' => 'Michigan', 'country_code' => 'US'],
            ['name' => 'Boston', 'state_name' => 'Massachusetts', 'country_code' => 'US'],
            ['name' => 'Memphis', 'state_name' => 'Tennessee', 'country_code' => 'US'],
            ['name' => 'Nashville', 'state_name' => 'Tennessee', 'country_code' => 'US'],
            ['name' => 'Portland', 'state_name' => 'Oregon', 'country_code' => 'US'],
            ['name' => 'Oklahoma City', 'state_name' => 'Oklahoma', 'country_code' => 'US'],
            ['name' => 'Las Vegas', 'state_name' => 'Nevada', 'country_code' => 'US'],
            ['name' => 'Louisville', 'state_name' => 'Kentucky', 'country_code' => 'US'],
            ['name' => 'Baltimore', 'state_name' => 'Maryland', 'country_code' => 'US'],
            ['name' => 'Milwaukee', 'state_name' => 'Wisconsin', 'country_code' => 'US'],
            ['name' => 'Albuquerque', 'state_name' => 'New Mexico', 'country_code' => 'US'],
            ['name' => 'Tucson', 'state_name' => 'Arizona', 'country_code' => 'US'],
            ['name' => 'Fresno', 'state_name' => 'California', 'country_code' => 'US'],
            ['name' => 'Atlanta', 'state_name' => 'Georgia', 'country_code' => 'US'],
            ['name' => 'Sacramento', 'state_name' => 'California', 'country_code' => 'US'],
            ['name' => 'Mesa', 'state_name' => 'Arizona', 'country_code' => 'US'],
            ['name' => 'Kansas City', 'state_name' => 'Missouri', 'country_code' => 'US'],
            ['name' => 'Colorado Springs', 'state_name' => 'Colorado', 'country_code' => 'US'],
            ['name' => 'Omaha', 'state_name' => 'Nebraska', 'country_code' => 'US'],
            ['name' => 'Raleigh', 'state_name' => 'North Carolina', 'country_code' => 'US'],
            ['name' => 'Minneapolis', 'state_name' => 'Minnesota', 'country_code' => 'US'],
            ['name' => 'Cleveland', 'state_name' => 'Ohio', 'country_code' => 'US'],
            ['name' => 'Wichita', 'state_name' => 'Kansas', 'country_code' => 'US'],
            ['name' => 'Arlington', 'state_name' => 'Texas', 'country_code' => 'US'],
            ['name' => 'New Orleans', 'state_name' => 'Louisiana', 'country_code' => 'US'],
            ['name' => 'Honolulu', 'state_name' => 'Hawaii', 'country_code' => 'US'],
            ['name' => 'Anchorage', 'state_name' => 'Alaska', 'country_code' => 'US'],
            ['name' => 'Washington DC', 'state_name' => 'Washington DC', 'country_code' => 'US'],

            // United Kingdom - Major cities
            ['name' => 'London', 'state_name' => 'England', 'country_code' => 'GB'],
            ['name' => 'Manchester', 'state_name' => 'England', 'country_code' => 'GB'],
            ['name' => 'Birmingham', 'state_name' => 'England', 'country_code' => 'GB'],
            ['name' => 'Leeds', 'state_name' => 'England', 'country_code' => 'GB'],
            ['name' => 'Liverpool', 'state_name' => 'England', 'country_code' => 'GB'],
            ['name' => 'Newcastle', 'state_name' => 'England', 'country_code' => 'GB'],
            ['name' => 'Sheffield', 'state_name' => 'England', 'country_code' => 'GB'],
            ['name' => 'Bristol', 'state_name' => 'England', 'country_code' => 'GB'],
            ['name' => 'Nottingham', 'state_name' => 'England', 'country_code' => 'GB'],
            ['name' => 'Leicester', 'state_name' => 'England', 'country_code' => 'GB'],
            ['name' => 'Edinburgh', 'state_name' => 'Scotland', 'country_code' => 'GB'],
            ['name' => 'Glasgow', 'state_name' => 'Scotland', 'country_code' => 'GB'],
            ['name' => 'Aberdeen', 'state_name' => 'Scotland', 'country_code' => 'GB'],
            ['name' => 'Cardiff', 'state_name' => 'Wales', 'country_code' => 'GB'],
            ['name' => 'Swansea', 'state_name' => 'Wales', 'country_code' => 'GB'],
            ['name' => 'Belfast', 'state_name' => 'Northern Ireland', 'country_code' => 'GB'],

            // Canada - Major cities
            ['name' => 'Toronto', 'state_name' => 'Ontario', 'country_code' => 'CA'],
            ['name' => 'Ottawa', 'state_name' => 'Ontario', 'country_code' => 'CA'],
            ['name' => 'Mississauga', 'state_name' => 'Ontario', 'country_code' => 'CA'],
            ['name' => 'Hamilton', 'state_name' => 'Ontario', 'country_code' => 'CA'],
            ['name' => 'Vancouver', 'state_name' => 'British Columbia', 'country_code' => 'CA'],
            ['name' => 'Victoria', 'state_name' => 'British Columbia', 'country_code' => 'CA'],
            ['name' => 'Surrey', 'state_name' => 'British Columbia', 'country_code' => 'CA'],
            ['name' => 'Burnaby', 'state_name' => 'British Columbia', 'country_code' => 'CA'],
            ['name' => 'Montreal', 'state_name' => 'Quebec', 'country_code' => 'CA'],
            ['name' => 'Quebec City', 'state_name' => 'Quebec', 'country_code' => 'CA'],
            ['name' => 'Laval', 'state_name' => 'Quebec', 'country_code' => 'CA'],
            ['name' => 'Calgary', 'state_name' => 'Alberta', 'country_code' => 'CA'],
            ['name' => 'Edmonton', 'state_name' => 'Alberta', 'country_code' => 'CA'],
            ['name' => 'Winnipeg', 'state_name' => 'Manitoba', 'country_code' => 'CA'],
            ['name' => 'Halifax', 'state_name' => 'Nova Scotia', 'country_code' => 'CA'],
            ['name' => 'Saskatoon', 'state_name' => 'Saskatchewan', 'country_code' => 'CA'],
            ['name' => 'Regina', 'state_name' => 'Saskatchewan', 'country_code' => 'CA'],
            ['name' => 'St. John\'s', 'state_name' => 'Newfoundland and Labrador', 'country_code' => 'CA'],
            ['name' => 'Fredericton', 'state_name' => 'New Brunswick', 'country_code' => 'CA'],
            ['name' => 'Charlottetown', 'state_name' => 'Prince Edward Island', 'country_code' => 'CA'],

            // Australia - Major cities
            ['name' => 'Sydney', 'state_name' => 'New South Wales', 'country_code' => 'AU'],
            ['name' => 'Melbourne', 'state_name' => 'Victoria', 'country_code' => 'AU'],
            ['name' => 'Brisbane', 'state_name' => 'Queensland', 'country_code' => 'AU'],
            ['name' => 'Perth', 'state_name' => 'Western Australia', 'country_code' => 'AU'],
            ['name' => 'Adelaide', 'state_name' => 'South Australia', 'country_code' => 'AU'],
            ['name' => 'Gold Coast', 'state_name' => 'Queensland', 'country_code' => 'AU'],
            ['name' => 'Canberra', 'state_name' => 'Australian Capital Territory', 'country_code' => 'AU'],
            ['name' => 'Newcastle', 'state_name' => 'New South Wales', 'country_code' => 'AU'],
            ['name' => 'Wollongong', 'state_name' => 'New South Wales', 'country_code' => 'AU'],
            ['name' => 'Hobart', 'state_name' => 'Tasmania', 'country_code' => 'AU'],
            ['name' => 'Darwin', 'state_name' => 'Northern Territory', 'country_code' => 'AU'],

            // Germany - Major cities
            ['name' => 'Berlin', 'state_name' => 'Berlin', 'country_code' => 'DE'],
            ['name' => 'Munich', 'state_name' => 'Bavaria', 'country_code' => 'DE'],
            ['name' => 'Hamburg', 'state_name' => 'Hamburg', 'country_code' => 'DE'],
            ['name' => 'Cologne', 'state_name' => 'North Rhine-Westphalia', 'country_code' => 'DE'],
            ['name' => 'Frankfurt', 'state_name' => 'Hesse', 'country_code' => 'DE'],
            ['name' => 'Stuttgart', 'state_name' => 'Baden-Württemberg', 'country_code' => 'DE'],
            ['name' => 'Düsseldorf', 'state_name' => 'North Rhine-Westphalia', 'country_code' => 'DE'],
            ['name' => 'Dortmund', 'state_name' => 'North Rhine-Westphalia', 'country_code' => 'DE'],
            ['name' => 'Essen', 'state_name' => 'North Rhine-Westphalia', 'country_code' => 'DE'],
            ['name' => 'Leipzig', 'state_name' => 'Saxony', 'country_code' => 'DE'],
            ['name' => 'Bremen', 'state_name' => 'Bremen', 'country_code' => 'DE'],
            ['name' => 'Dresden', 'state_name' => 'Saxony', 'country_code' => 'DE'],
            ['name' => 'Hanover', 'state_name' => 'Lower Saxony', 'country_code' => 'DE'],
            ['name' => 'Nuremberg', 'state_name' => 'Bavaria', 'country_code' => 'DE'],
            ['name' => 'Duisburg', 'state_name' => 'North Rhine-Westphalia', 'country_code' => 'DE'],
            ['name' => 'Bochum', 'state_name' => 'North Rhine-Westphalia', 'country_code' => 'DE'],
            ['name' => 'Wuppertal', 'state_name' => 'North Rhine-Westphalia', 'country_code' => 'DE'],
            ['name' => 'Bielefeld', 'state_name' => 'North Rhine-Westphalia', 'country_code' => 'DE'],
            ['name' => 'Bonn', 'state_name' => 'North Rhine-Westphalia', 'country_code' => 'DE'],
            ['name' => 'Münster', 'state_name' => 'North Rhine-Westphalia', 'country_code' => 'DE'],
            ['name' => 'Karlsruhe', 'state_name' => 'Baden-Württemberg', 'country_code' => 'DE'],
            ['name' => 'Mannheim', 'state_name' => 'Baden-Württemberg', 'country_code' => 'DE'],
            ['name' => 'Augsburg', 'state_name' => 'Bavaria', 'country_code' => 'DE'],
            ['name' => 'Wiesbaden', 'state_name' => 'Hesse', 'country_code' => 'DE'],
            ['name' => 'Gelsenkirchen', 'state_name' => 'North Rhine-Westphalia', 'country_code' => 'DE'],
            ['name' => 'Mönchengladbach', 'state_name' => 'North Rhine-Westphalia', 'country_code' => 'DE'],
            ['name' => 'Braunschweig', 'state_name' => 'Lower Saxony', 'country_code' => 'DE'],
            ['name' => 'Kiel', 'state_name' => 'Schleswig-Holstein', 'country_code' => 'DE'],
            ['name' => 'Chemnitz', 'state_name' => 'Saxony', 'country_code' => 'DE'],
            ['name' => 'Aachen', 'state_name' => 'North Rhine-Westphalia', 'country_code' => 'DE'],
            ['name' => 'Halle (Saale)', 'state_name' => 'Saxony-Anhalt', 'country_code' => 'DE'],
            ['name' => 'Magdeburg', 'state_name' => 'Saxony-Anhalt', 'country_code' => 'DE'],
            ['name' => 'Freiburg', 'state_name' => 'Baden-Württemberg', 'country_code' => 'DE'],
            ['name' => 'Krefeld', 'state_name' => 'North Rhine-Westphalia', 'country_code' => 'DE'],
            ['name' => 'Lübeck', 'state_name' => 'Schleswig-Holstein', 'country_code' => 'DE'],
            ['name' => 'Oberhausen', 'state_name' => 'North Rhine-Westphalia', 'country_code' => 'DE'],
            ['name' => 'Erfurt', 'state_name' => 'Thuringia', 'country_code' => 'DE'],
            ['name' => 'Mainz', 'state_name' => 'Rhineland-Palatinate', 'country_code' => 'DE'],
            ['name' => 'Rostock', 'state_name' => 'Mecklenburg-Vorpommern', 'country_code' => 'DE'],
            ['name' => 'Kassel', 'state_name' => 'Hesse', 'country_code' => 'DE'],
            ['name' => 'Hagen', 'state_name' => 'North Rhine-Westphalia', 'country_code' => 'DE'],
            ['name' => 'Saarbrücken', 'state_name' => 'Saarland', 'country_code' => 'DE'],
            ['name' => 'Hamm', 'state_name' => 'North Rhine-Westphalia', 'country_code' => 'DE'],
            ['name' => 'Potsdam', 'state_name' => 'Brandenburg', 'country_code' => 'DE'],

            // France - Major cities
            ['name' => 'Paris', 'state_name' => 'Île-de-France', 'country_code' => 'FR'],
            ['name' => 'Marseille', 'state_name' => 'Provence-Alpes-Côte d\'Azur', 'country_code' => 'FR'],
            ['name' => 'Lyon', 'state_name' => 'Auvergne-Rhône-Alpes', 'country_code' => 'FR'],
            ['name' => 'Toulouse', 'state_name' => 'Occitanie', 'country_code' => 'FR'],
            ['name' => 'Nice', 'state_name' => 'Provence-Alpes-Côte d\'Azur', 'country_code' => 'FR'],
            ['name' => 'Nantes', 'state_name' => 'Pays de la Loire', 'country_code' => 'FR'],
            ['name' => 'Strasbourg', 'state_name' => 'Grand Est', 'country_code' => 'FR'],
            ['name' => 'Montpellier', 'state_name' => 'Occitanie', 'country_code' => 'FR'],
            ['name' => 'Bordeaux', 'state_name' => 'Nouvelle-Aquitaine', 'country_code' => 'FR'],
            ['name' => 'Lille', 'state_name' => 'Hauts-de-France', 'country_code' => 'FR'],
            ['name' => 'Rennes', 'state_name' => 'Brittany', 'country_code' => 'FR'],
            ['name' => 'Reims', 'state_name' => 'Grand Est', 'country_code' => 'FR'],
            ['name' => 'Le Havre', 'state_name' => 'Normandy', 'country_code' => 'FR'],
            ['name' => 'Saint-Étienne', 'state_name' => 'Auvergne-Rhône-Alpes', 'country_code' => 'FR'],
            ['name' => 'Toulon', 'state_name' => 'Provence-Alpes-Côte d\'Azur', 'country_code' => 'FR'],
            ['name' => 'Grenoble', 'state_name' => 'Auvergne-Rhône-Alpes', 'country_code' => 'FR'],
            ['name' => 'Dijon', 'state_name' => 'Bourgogne-Franche-Comté', 'country_code' => 'FR'],
            ['name' => 'Angers', 'state_name' => 'Pays de la Loire', 'country_code' => 'FR'],
            ['name' => 'Nîmes', 'state_name' => 'Occitanie', 'country_code' => 'FR'],
            ['name' => 'Villeurbanne', 'state_name' => 'Auvergne-Rhône-Alpes', 'country_code' => 'FR'],
            ['name' => 'Aix-en-Provence', 'state_name' => 'Provence-Alpes-Côte d\'Azur', 'country_code' => 'FR'],
            ['name' => 'Le Mans', 'state_name' => 'Pays de la Loire', 'country_code' => 'FR'],
            ['name' => 'Clermont-Ferrand', 'state_name' => 'Auvergne-Rhône-Alpes', 'country_code' => 'FR'],
            ['name' => 'Brest', 'state_name' => 'Brittany', 'country_code' => 'FR'],
            ['name' => 'Tours', 'state_name' => 'Centre-Val de Loire', 'country_code' => 'FR'],
            ['name' => 'Amiens', 'state_name' => 'Hauts-de-France', 'country_code' => 'FR'],
            ['name' => 'Limoges', 'state_name' => 'Nouvelle-Aquitaine', 'country_code' => 'FR'],
            ['name' => 'Annecy', 'state_name' => 'Auvergne-Rhône-Alpes', 'country_code' => 'FR'],
            ['name' => 'Perpignan', 'state_name' => 'Occitanie', 'country_code' => 'FR'],
            ['name' => 'Boulogne-Billancourt', 'state_name' => 'Île-de-France', 'country_code' => 'FR'],
            ['name' => 'Metz', 'state_name' => 'Grand Est', 'country_code' => 'FR'],
            ['name' => 'Besançon', 'state_name' => 'Bourgogne-Franche-Comté', 'country_code' => 'FR'],
            ['name' => 'Orléans', 'state_name' => 'Centre-Val de Loire', 'country_code' => 'FR'],
            ['name' => 'Saint-Denis', 'state_name' => 'Île-de-France', 'country_code' => 'FR'],
            ['name' => 'Argenteuil', 'state_name' => 'Île-de-France', 'country_code' => 'FR'],
            ['name' => 'Mulhouse', 'state_name' => 'Grand Est', 'country_code' => 'FR'],
            ['name' => 'Rouen', 'state_name' => 'Normandy', 'country_code' => 'FR'],
            ['name' => 'Caen', 'state_name' => 'Normandy', 'country_code' => 'FR'],
            ['name' => 'Nancy', 'state_name' => 'Grand Est', 'country_code' => 'FR'],

            // China - Major cities
            ['name' => 'Shanghai', 'state_name' => 'Shanghai', 'country_code' => 'CN'],
            ['name' => 'Beijing', 'state_name' => 'Beijing', 'country_code' => 'CN'],
            ['name' => 'Guangzhou', 'state_name' => 'Guangdong', 'country_code' => 'CN'],
            ['name' => 'Shenzhen', 'state_name' => 'Guangdong', 'country_code' => 'CN'],
            ['name' => 'Dongguan', 'state_name' => 'Guangdong', 'country_code' => 'CN'],
            ['name' => 'Tianjin', 'state_name' => 'Tianjin', 'country_code' => 'CN'],
            ['name' => 'Wuhan', 'state_name' => 'Hubei', 'country_code' => 'CN'],
            ['name' => 'Chengdu', 'state_name' => 'Sichuan', 'country_code' => 'CN'],
            ['name' => 'Nanjing', 'state_name' => 'Jiangsu', 'country_code' => 'CN'],
            ['name' => 'Hangzhou', 'state_name' => 'Zhejiang', 'country_code' => 'CN'],
            ['name' => 'Ningbo', 'state_name' => 'Zhejiang', 'country_code' => 'CN'],
            ['name' => 'Suzhou', 'state_name' => 'Jiangsu', 'country_code' => 'CN'],
            ['name' => 'Qingdao', 'state_name' => 'Shandong', 'country_code' => 'CN'],
            ['name' => 'Dalian', 'state_name' => 'Liaoning', 'country_code' => 'CN'],
            ['name' => 'Shenyang', 'state_name' => 'Liaoning', 'country_code' => 'CN'],
            ['name' => 'Changchun', 'state_name' => 'Jilin', 'country_code' => 'CN'],
            ['name' => 'Harbin', 'state_name' => 'Heilongjiang', 'country_code' => 'CN'],
            ['name' => 'Jinan', 'state_name' => 'Shandong', 'country_code' => 'CN'],
            ['name' => 'Zhengzhou', 'state_name' => 'Henan', 'country_code' => 'CN'],
            ['name' => 'Xi\'an', 'state_name' => 'Shaanxi', 'country_code' => 'CN'],
            ['name' => 'Chongqing', 'state_name' => 'Chongqing', 'country_code' => 'CN'],
            ['name' => 'Foshan', 'state_name' => 'Guangdong', 'country_code' => 'CN'],
            ['name' => 'Fuzhou', 'state_name' => 'Fujian', 'country_code' => 'CN'],
            ['name' => 'Xiamen', 'state_name' => 'Fujian', 'country_code' => 'CN'],
            ['name' => 'Kunming', 'state_name' => 'Yunnan', 'country_code' => 'CN'],
            ['name' => 'Hefei', 'state_name' => 'Anhui', 'country_code' => 'CN'],
            ['name' => 'Changsha', 'state_name' => 'Hunan', 'country_code' => 'CN'],
            ['name' => 'Shijiazhuang', 'state_name' => 'Hebei', 'country_code' => 'CN'],
            ['name' => 'Taiyuan', 'state_name' => 'Shanxi', 'country_code' => 'CN'],
            ['name' => 'Wuxi', 'state_name' => 'Jiangsu', 'country_code' => 'CN'],
            ['name' => 'Changzhou', 'state_name' => 'Jiangsu', 'country_code' => 'CN'],
            ['name' => 'Nantong', 'state_name' => 'Jiangsu', 'country_code' => 'CN'],
            ['name' => 'Yantai', 'state_name' => 'Shandong', 'country_code' => 'CN'],
            ['name' => 'Wenzhou', 'state_name' => 'Zhejiang', 'country_code' => 'CN'],
            ['name' => 'Jiaxing', 'state_name' => 'Zhejiang', 'country_code' => 'CN'],
            ['name' => 'Shaoxing', 'state_name' => 'Zhejiang', 'country_code' => 'CN'],
            ['name' => 'Taizhou', 'state_name' => 'Zhejiang', 'country_code' => 'CN'],
            ['name' => 'Jinhua', 'state_name' => 'Zhejiang', 'country_code' => 'CN'],
            ['name' => 'Quanzhou', 'state_name' => 'Fujian', 'country_code' => 'CN'],
            ['name' => 'Zhongshan', 'state_name' => 'Guangdong', 'country_code' => 'CN'],
            ['name' => 'Huizhou', 'state_name' => 'Guangdong', 'country_code' => 'CN'],
            ['name' => 'Zhuhai', 'state_name' => 'Guangdong', 'country_code' => 'CN'],
            ['name' => 'Jiangmen', 'state_name' => 'Guangdong', 'country_code' => 'CN'],

            // Japan - Major cities
            ['name' => 'Tokyo', 'state_name' => 'Tokyo', 'country_code' => 'JP'],
            ['name' => 'Yokohama', 'state_name' => 'Kanagawa', 'country_code' => 'JP'],
            ['name' => 'Osaka', 'state_name' => 'Osaka', 'country_code' => 'JP'],
            ['name' => 'Nagoya', 'state_name' => 'Aichi', 'country_code' => 'JP'],
            ['name' => 'Sapporo', 'state_name' => 'Hokkaido', 'country_code' => 'JP'],
            ['name' => 'Fukuoka', 'state_name' => 'Fukuoka', 'country_code' => 'JP'],
            ['name' => 'Kobe', 'state_name' => 'Hyogo', 'country_code' => 'JP'],
            ['name' => 'Kawasaki', 'state_name' => 'Kanagawa', 'country_code' => 'JP'],
            ['name' => 'Kyoto', 'state_name' => 'Kyoto', 'country_code' => 'JP'],
            ['name' => 'Saitama', 'state_name' => 'Saitama', 'country_code' => 'JP'],
            ['name' => 'Hiroshima', 'state_name' => 'Hiroshima', 'country_code' => 'JP'],
            ['name' => 'Sendai', 'state_name' => 'Miyagi', 'country_code' => 'JP'],
            ['name' => 'Chiba', 'state_name' => 'Chiba', 'country_code' => 'JP'],
            ['name' => 'Kitakyushu', 'state_name' => 'Fukuoka', 'country_code' => 'JP'],
            ['name' => 'Sakai', 'state_name' => 'Osaka', 'country_code' => 'JP'],
            ['name' => 'Hamamatsu', 'state_name' => 'Shizuoka', 'country_code' => 'JP'],
            ['name' => 'Niigata', 'state_name' => 'Niigata', 'country_code' => 'JP'],
            ['name' => 'Shizuoka', 'state_name' => 'Shizuoka', 'country_code' => 'JP'],
            ['name' => 'Okayama', 'state_name' => 'Okayama', 'country_code' => 'JP'],
            ['name' => 'Sagamihara', 'state_name' => 'Kanagawa', 'country_code' => 'JP'],
            ['name' => 'Kumamoto', 'state_name' => 'Kumamoto', 'country_code' => 'JP'],
            ['name' => 'Kagoshima', 'state_name' => 'Kagoshima', 'country_code' => 'JP'],

            // Brazil - Major cities
            ['name' => 'São Paulo', 'state_name' => 'São Paulo', 'country_code' => 'BR'],
            ['name' => 'Rio de Janeiro', 'state_name' => 'Rio de Janeiro', 'country_code' => 'BR'],
            ['name' => 'Brasília', 'state_name' => 'Federal District', 'country_code' => 'BR'],
            ['name' => 'Salvador', 'state_name' => 'Bahia', 'country_code' => 'BR'],
            ['name' => 'Fortaleza', 'state_name' => 'Ceará', 'country_code' => 'BR'],
            ['name' => 'Belo Horizonte', 'state_name' => 'Minas Gerais', 'country_code' => 'BR'],
            ['name' => 'Manaus', 'state_name' => 'Amazonas', 'country_code' => 'BR'],
            ['name' => 'Curitiba', 'state_name' => 'Paraná', 'country_code' => 'BR'],
            ['name' => 'Recife', 'state_name' => 'Pernambuco', 'country_code' => 'BR'],
            ['name' => 'Porto Alegre', 'state_name' => 'Rio Grande do Sul', 'country_code' => 'BR'],
            ['name' => 'Belém', 'state_name' => 'Pará', 'country_code' => 'BR'],
            ['name' => 'Goiânia', 'state_name' => 'Goiás', 'country_code' => 'BR'],
            ['name' => 'Guarulhos', 'state_name' => 'São Paulo', 'country_code' => 'BR'],
            ['name' => 'Campinas', 'state_name' => 'São Paulo', 'country_code' => 'BR'],
            ['name' => 'São Luís', 'state_name' => 'Maranhão', 'country_code' => 'BR'],
            ['name' => 'São Gonçalo', 'state_name' => 'Rio de Janeiro', 'country_code' => 'BR'],
            ['name' => 'Maceió', 'state_name' => 'Alagoas', 'country_code' => 'BR'],
            ['name' => 'Duque de Caxias', 'state_name' => 'Rio de Janeiro', 'country_code' => 'BR'],
            ['name' => 'Natal', 'state_name' => 'Rio Grande do Norte', 'country_code' => 'BR'],
            ['name' => 'Campo Grande', 'state_name' => 'Mato Grosso do Sul', 'country_code' => 'BR'],
            ['name' => 'Teresina', 'state_name' => 'Piauí', 'country_code' => 'BR'],

            // UAE - Major cities
            ['name' => 'Dubai', 'state_name' => 'Dubai', 'country_code' => 'AE'],
            ['name' => 'Abu Dhabi', 'state_name' => 'Abu Dhabi', 'country_code' => 'AE'],
            ['name' => 'Sharjah', 'state_name' => 'Sharjah', 'country_code' => 'AE'],
            ['name' => 'Al Ain', 'state_name' => 'Abu Dhabi', 'country_code' => 'AE'],
            ['name' => 'Ajman', 'state_name' => 'Ajman', 'country_code' => 'AE'],
            ['name' => 'Ras Al Khaimah', 'state_name' => 'Ras Al Khaimah', 'country_code' => 'AE'],
            ['name' => 'Fujairah', 'state_name' => 'Fujairah', 'country_code' => 'AE'],
            ['name' => 'Umm Al Quwain', 'state_name' => 'Umm Al Quwain', 'country_code' => 'AE'],

            // Saudi Arabia - Major cities
            ['name' => 'Riyadh', 'state_name' => 'Riyadh Province', 'country_code' => 'SA'],
            ['name' => 'Jeddah', 'state_name' => 'Makkah Province', 'country_code' => 'SA'],
            ['name' => 'Mecca', 'state_name' => 'Makkah Province', 'country_code' => 'SA'],
            ['name' => 'Medina', 'state_name' => 'Medina Province', 'country_code' => 'SA'],
            ['name' => 'Dammam', 'state_name' => 'Eastern Province', 'country_code' => 'SA'],
            ['name' => 'Khobar', 'state_name' => 'Eastern Province', 'country_code' => 'SA'],
            ['name' => 'Tabuk', 'state_name' => 'Tabuk Province', 'country_code' => 'SA'],
            ['name' => 'Buraidah', 'state_name' => 'Qassim Province', 'country_code' => 'SA'],
            ['name' => 'Khamis Mushait', 'state_name' => 'Asir Province', 'country_code' => 'SA'],
            ['name' => 'Hail', 'state_name' => 'Hail Province', 'country_code' => 'SA'],
            ['name' => 'Abha', 'state_name' => 'Asir Province', 'country_code' => 'SA'],

            // Pakistan - Major cities
            ['name' => 'Karachi', 'state_name' => 'Sindh', 'country_code' => 'PK'],
            ['name' => 'Lahore', 'state_name' => 'Punjab', 'country_code' => 'PK'],
            ['name' => 'Faisalabad', 'state_name' => 'Punjab', 'country_code' => 'PK'],
            ['name' => 'Rawalpindi', 'state_name' => 'Punjab', 'country_code' => 'PK'],
            ['name' => 'Gujranwala', 'state_name' => 'Punjab', 'country_code' => 'PK'],
            ['name' => 'Multan', 'state_name' => 'Punjab', 'country_code' => 'PK'],
            ['name' => 'Sialkot', 'state_name' => 'Punjab', 'country_code' => 'PK'],
            ['name' => 'Peshawar', 'state_name' => 'Khyber Pakhtunkhwa', 'country_code' => 'PK'],
            ['name' => 'Abbottabad', 'state_name' => 'Khyber Pakhtunkhwa', 'country_code' => 'PK'],
            ['name' => 'Quetta', 'state_name' => 'Balochistan', 'country_code' => 'PK'],
            ['name' => 'Islamabad', 'state_name' => 'Islamabad Capital Territory', 'country_code' => 'PK'],
            ['name' => 'Hyderabad', 'state_name' => 'Sindh', 'country_code' => 'PK'],

            // Bangladesh - Major cities
            ['name' => 'Dhaka', 'state_name' => 'Dhaka Division', 'country_code' => 'BD'],
            ['name' => 'Chittagong', 'state_name' => 'Chittagong Division', 'country_code' => 'BD'],
            ['name' => 'Khulna', 'state_name' => 'Khulna Division', 'country_code' => 'BD'],
            ['name' => 'Rajshahi', 'state_name' => 'Rajshahi Division', 'country_code' => 'BD'],
            ['name' => 'Sylhet', 'state_name' => 'Sylhet Division', 'country_code' => 'BD'],
            ['name' => 'Barisal', 'state_name' => 'Barisal Division', 'country_code' => 'BD'],
            ['name' => 'Rangpur', 'state_name' => 'Rangpur Division', 'country_code' => 'BD'],
            ['name' => 'Comilla', 'state_name' => 'Chittagong Division', 'country_code' => 'BD'],
            ['name' => 'Narayanganj', 'state_name' => 'Dhaka Division', 'country_code' => 'BD'],
            ['name' => 'Gazipur', 'state_name' => 'Dhaka Division', 'country_code' => 'BD'],

            // Turkey - Major cities
            ['name' => 'Istanbul', 'state_name' => 'Istanbul', 'country_code' => 'TR'],
            ['name' => 'Ankara', 'state_name' => 'Ankara', 'country_code' => 'TR'],
            ['name' => 'Izmir', 'state_name' => 'Izmir', 'country_code' => 'TR'],
            ['name' => 'Bursa', 'state_name' => 'Bursa', 'country_code' => 'TR'],
            ['name' => 'Adana', 'state_name' => 'Adana', 'country_code' => 'TR'],
            ['name' => 'Gaziantep', 'state_name' => 'Gaziantep', 'country_code' => 'TR'],
            ['name' => 'Konya', 'state_name' => 'Konya', 'country_code' => 'TR'],
            ['name' => 'Antalya', 'state_name' => 'Antalya', 'country_code' => 'TR'],
            ['name' => 'Mersin', 'state_name' => 'Mersin', 'country_code' => 'TR'],
            ['name' => 'Diyarbakir', 'state_name' => 'Diyarbakir', 'country_code' => 'TR'],
            ['name' => 'Kayseri', 'state_name' => 'Kayseri', 'country_code' => 'TR'],
            ['name' => 'Eskisehir', 'state_name' => 'Eskisehir', 'country_code' => 'TR'],
            ['name' => 'Samsun', 'state_name' => 'Samsun', 'country_code' => 'TR'],
            ['name' => 'Denizli', 'state_name' => 'Denizli', 'country_code' => 'TR'],

            // South Korea - Major cities
            ['name' => 'Seoul', 'state_name' => 'Seoul', 'country_code' => 'KR'],
            ['name' => 'Busan', 'state_name' => 'Busan', 'country_code' => 'KR'],
            ['name' => 'Incheon', 'state_name' => 'Incheon', 'country_code' => 'KR'],
            ['name' => 'Daegu', 'state_name' => 'Daegu', 'country_code' => 'KR'],
            ['name' => 'Daejeon', 'state_name' => 'Daejeon', 'country_code' => 'KR'],
            ['name' => 'Gwangju', 'state_name' => 'Gwangju', 'country_code' => 'KR'],
            ['name' => 'Ulsan', 'state_name' => 'Ulsan', 'country_code' => 'KR'],
            ['name' => 'Suwon', 'state_name' => 'Gyeonggi-do', 'country_code' => 'KR'],
            ['name' => 'Changwon', 'state_name' => 'South Gyeongsang', 'country_code' => 'KR'],
            ['name' => 'Seongnam', 'state_name' => 'Gyeonggi-do', 'country_code' => 'KR'],
            ['name' => 'Goyang', 'state_name' => 'Gyeonggi-do', 'country_code' => 'KR'],
            ['name' => 'Yongin', 'state_name' => 'Gyeonggi-do', 'country_code' => 'KR'],

            // Additional European cities
            ['name' => 'Amsterdam', 'state_name' => 'North Holland', 'country_code' => 'NL'],
            ['name' => 'Rotterdam', 'state_name' => 'South Holland', 'country_code' => 'NL'],
            ['name' => 'The Hague', 'state_name' => 'South Holland', 'country_code' => 'NL'],
            ['name' => 'Utrecht', 'state_name' => 'Utrecht', 'country_code' => 'NL'],
            ['name' => 'Eindhoven', 'state_name' => 'North Brabant', 'country_code' => 'NL'],

            ['name' => 'Zurich', 'state_name' => 'Zurich', 'country_code' => 'CH'],
            ['name' => 'Geneva', 'state_name' => 'Geneva', 'country_code' => 'CH'],
            ['name' => 'Basel', 'state_name' => 'Basel-City', 'country_code' => 'CH'],
            ['name' => 'Bern', 'state_name' => 'Bern', 'country_code' => 'CH'],
            ['name' => 'Lausanne', 'state_name' => 'Vaud', 'country_code' => 'CH'],
            ['name' => 'Lucerne', 'state_name' => 'Lucerne', 'country_code' => 'CH'],

            ['name' => 'Vienna', 'state_name' => 'Vienna', 'country_code' => 'AT'],
            ['name' => 'Graz', 'state_name' => 'Styria', 'country_code' => 'AT'],
            ['name' => 'Linz', 'state_name' => 'Upper Austria', 'country_code' => 'AT'],
            ['name' => 'Salzburg', 'state_name' => 'Salzburg', 'country_code' => 'AT'],
            ['name' => 'Innsbruck', 'state_name' => 'Tyrol', 'country_code' => 'AT'],

            ['name' => 'Stockholm', 'state_name' => 'Stockholm County', 'country_code' => 'SE'],
            ['name' => 'Gothenburg', 'state_name' => 'Västra Götaland County', 'country_code' => 'SE'],
            ['name' => 'Malmö', 'state_name' => 'Skåne County', 'country_code' => 'SE'],
            ['name' => 'Uppsala', 'state_name' => 'Uppsala County', 'country_code' => 'SE'],

            ['name' => 'Oslo', 'state_name' => 'Oslo', 'country_code' => 'NO'],
            ['name' => 'Bergen', 'state_name' => 'Vestland', 'country_code' => 'NO'],
            ['name' => 'Trondheim', 'state_name' => 'Trøndelag', 'country_code' => 'NO'],
            ['name' => 'Stavanger', 'state_name' => 'Rogaland', 'country_code' => 'NO'],

            ['name' => 'Copenhagen', 'state_name' => 'Capital Region', 'country_code' => 'DK'],
            ['name' => 'Aarhus', 'state_name' => 'Central Denmark Region', 'country_code' => 'DK'],
            ['name' => 'Odense', 'state_name' => 'Region of Southern Denmark', 'country_code' => 'DK'],
            ['name' => 'Aalborg', 'state_name' => 'North Denmark Region', 'country_code' => 'DK'],

            ['name' => 'Helsinki', 'state_name' => 'Uusimaa', 'country_code' => 'FI'],
            ['name' => 'Espoo', 'state_name' => 'Uusimaa', 'country_code' => 'FI'],
            ['name' => 'Tampere', 'state_name' => 'Pirkanmaa', 'country_code' => 'FI'],
            ['name' => 'Vantaa', 'state_name' => 'Uusimaa', 'country_code' => 'FI'],
            ['name' => 'Oulu', 'state_name' => 'North Ostrobothnia', 'country_code' => 'FI'],
            ['name' => 'Turku', 'state_name' => 'Southwest Finland', 'country_code' => 'FI'],

            ['name' => 'Dublin', 'state_name' => 'Leinster', 'country_code' => 'IE'],
            ['name' => 'Cork', 'state_name' => 'Munster', 'country_code' => 'IE'],
            ['name' => 'Limerick', 'state_name' => 'Munster', 'country_code' => 'IE'],
            ['name' => 'Galway', 'state_name' => 'Connacht', 'country_code' => 'IE'],
            ['name' => 'Waterford', 'state_name' => 'Munster', 'country_code' => 'IE'],

            ['name' => 'Lisbon', 'state_name' => 'Lisbon', 'country_code' => 'PT'],
            ['name' => 'Porto', 'state_name' => 'Porto', 'country_code' => 'PT'],
            ['name' => 'Amadora', 'state_name' => 'Lisbon', 'country_code' => 'PT'],
            ['name' => 'Braga', 'state_name' => 'Braga', 'country_code' => 'PT'],
            ['name' => 'Setúbal', 'state_name' => 'Setúbal', 'country_code' => 'PT'],
            ['name' => 'Coimbra', 'state_name' => 'Coimbra', 'country_code' => 'PT'],
            ['name' => 'Funchal', 'state_name' => 'Madeira', 'country_code' => 'PT'],

            ['name' => 'Athens', 'state_name' => 'Attica', 'country_code' => 'GR'],
            ['name' => 'Thessaloniki', 'state_name' => 'Central Macedonia', 'country_code' => 'GR'],
            ['name' => 'Patras', 'state_name' => 'Western Greece', 'country_code' => 'GR'],
            ['name' => 'Heraklion', 'state_name' => 'Crete', 'country_code' => 'GR'],
            ['name' => 'Larissa', 'state_name' => 'Thessaly', 'country_code' => 'GR'],

            ['name' => 'Prague', 'state_name' => 'Prague', 'country_code' => 'CZ'],
            ['name' => 'Brno', 'state_name' => 'South Moravian', 'country_code' => 'CZ'],
            ['name' => 'Ostrava', 'state_name' => 'Moravian-Silesian', 'country_code' => 'CZ'],
            ['name' => 'Plzeň', 'state_name' => 'Plzeň', 'country_code' => 'CZ'],
            ['name' => 'Liberec', 'state_name' => 'Liberec', 'country_code' => 'CZ'],

            ['name' => 'Warsaw', 'state_name' => 'Masovian Voivodeship', 'country_code' => 'PL'],
            ['name' => 'Kraków', 'state_name' => 'Lesser Poland Voivodeship', 'country_code' => 'PL'],
            ['name' => 'Łódź', 'state_name' => 'Łódź Voivodeship', 'country_code' => 'PL'],
            ['name' => 'Wrocław', 'state_name' => 'Lower Silesian Voivodeship', 'country_code' => 'PL'],
            ['name' => 'Poznań', 'state_name' => 'Greater Poland Voivodeship', 'country_code' => 'PL'],
            ['name' => 'Gdańsk', 'state_name' => 'Pomeranian Voivodeship', 'country_code' => 'PL'],

            ['name' => 'Brussels', 'state_name' => 'Brussels', 'country_code' => 'BE'],
            ['name' => 'Antwerp', 'state_name' => 'Antwerp', 'country_code' => 'BE'],
            ['name' => 'Ghent', 'state_name' => 'East Flanders', 'country_code' => 'BE'],
            ['name' => 'Charleroi', 'state_name' => 'Hainaut', 'country_code' => 'BE'],
            ['name' => 'Liège', 'state_name' => 'Liège', 'country_code' => 'BE'],
            ['name' => 'Bruges', 'state_name' => 'West Flanders', 'country_code' => 'BE'],

            ['name' => 'Budapest', 'state_name' => 'Central Hungary', 'country_code' => 'HU'],
            ['name' => 'Debrecen', 'state_name' => 'Hajdú-Bihar', 'country_code' => 'HU'],
            ['name' => 'Szeged', 'state_name' => 'Csongrád-Csanád', 'country_code' => 'HU'],
            ['name' => 'Miskolc', 'state_name' => 'Borsod-Abaúj-Zemplén', 'country_code' => 'HU'],
            ['name' => 'Pécs', 'state_name' => 'Baranya', 'country_code' => 'HU'],

            ['name' => 'Rome', 'state_name' => 'Lazio', 'country_code' => 'IT'],
            ['name' => 'Milan', 'state_name' => 'Lombardy', 'country_code' => 'IT'],
            ['name' => 'Naples', 'state_name' => 'Campania', 'country_code' => 'IT'],
            ['name' => 'Turin', 'state_name' => 'Piedmont', 'country_code' => 'IT'],
            ['name' => 'Palermo', 'state_name' => 'Sicily', 'country_code' => 'IT'],
            ['name' => 'Genoa', 'state_name' => 'Liguria', 'country_code' => 'IT'],
            ['name' => 'Bologna', 'state_name' => 'Emilia-Romagna', 'country_code' => 'IT'],
            ['name' => 'Florence', 'state_name' => 'Tuscany', 'country_code' => 'IT'],
            ['name' => 'Bari', 'state_name' => 'Apulia', 'country_code' => 'IT'],
            ['name' => 'Catania', 'state_name' => 'Sicily', 'country_code' => 'IT'],
            ['name' => 'Venice', 'state_name' => 'Veneto', 'country_code' => 'IT'],
            ['name' => 'Verona', 'state_name' => 'Veneto', 'country_code' => 'IT'],
            ['name' => 'Messina', 'state_name' => 'Sicily', 'country_code' => 'IT'],
            ['name' => 'Padua', 'state_name' => 'Veneto', 'country_code' => 'IT'],
            ['name' => 'Trieste', 'state_name' => 'Friuli-Venezia Giulia', 'country_code' => 'IT'],
            ['name' => 'Brescia', 'state_name' => 'Lombardy', 'country_code' => 'IT'],
            ['name' => 'Parma', 'state_name' => 'Emilia-Romagna', 'country_code' => 'IT'],
            ['name' => 'Taranto', 'state_name' => 'Apulia', 'country_code' => 'IT'],
            ['name' => 'Prato', 'state_name' => 'Tuscany', 'country_code' => 'IT'],
            ['name' => 'Modena', 'state_name' => 'Emilia-Romagna', 'country_code' => 'IT'],
            ['name' => 'Reggio Calabria', 'state_name' => 'Calabria', 'country_code' => 'IT'],
            ['name' => 'Rimini', 'state_name' => 'Emilia-Romagna', 'country_code' => 'IT'],
            ['name' => 'Livorno', 'state_name' => 'Tuscany', 'country_code' => 'IT'],
            ['name' => 'Cagliari', 'state_name' => 'Sardinia', 'country_code' => 'IT'],

            ['name' => 'Madrid', 'state_name' => 'Madrid', 'country_code' => 'ES'],
            ['name' => 'Barcelona', 'state_name' => 'Catalonia', 'country_code' => 'ES'],
            ['name' => 'Valencia', 'state_name' => 'Valencia', 'country_code' => 'ES'],
            ['name' => 'Seville', 'state_name' => 'Andalusia', 'country_code' => 'ES'],
            ['name' => 'Zaragoza', 'state_name' => 'Aragon', 'country_code' => 'ES'],
            ['name' => 'Málaga', 'state_name' => 'Andalusia', 'country_code' => 'ES'],
            ['name' => 'Murcia', 'state_name' => 'Region of Murcia', 'country_code' => 'ES'],
            ['name' => 'Palma', 'state_name' => 'Balearic Islands', 'country_code' => 'ES'],
            ['name' => 'Las Palmas', 'state_name' => 'Canary Islands', 'country_code' => 'ES'],
            ['name' => 'Bilbao', 'state_name' => 'Basque Country', 'country_code' => 'ES'],
            ['name' => 'Alicante', 'state_name' => 'Valencia', 'country_code' => 'ES'],
            ['name' => 'Córdoba', 'state_name' => 'Andalusia', 'country_code' => 'ES'],
            ['name' => 'Valladolid', 'state_name' => 'Castile and León', 'country_code' => 'ES'],
            ['name' => 'Vigo', 'state_name' => 'Galicia', 'country_code' => 'ES'],
            ['name' => 'Gijón', 'state_name' => 'Asturias', 'country_code' => 'ES'],
            ['name' => 'L\'Hospitalet de Llobregat', 'state_name' => 'Catalonia', 'country_code' => 'ES'],
            ['name' => 'Vitoria-Gasteiz', 'state_name' => 'Basque Country', 'country_code' => 'ES'],
            ['name' => 'La Coruña', 'state_name' => 'Galicia', 'country_code' => 'ES'],
            ['name' => 'Granada', 'state_name' => 'Andalusia', 'country_code' => 'ES'],
            ['name' => 'Elche', 'state_name' => 'Valencia', 'country_code' => 'ES'],

            ['name' => 'Mexico City', 'state_name' => 'Mexico City', 'country_code' => 'MX'],
            ['name' => 'Guadalajara', 'state_name' => 'Jalisco', 'country_code' => 'MX'],
            ['name' => 'Monterrey', 'state_name' => 'Nuevo León', 'country_code' => 'MX'],
            ['name' => 'Puebla', 'state_name' => 'Puebla', 'country_code' => 'MX'],
            ['name' => 'Tijuana', 'state_name' => 'Baja California', 'country_code' => 'MX'],
            ['name' => 'León', 'state_name' => 'Guanajuato', 'country_code' => 'MX'],
            ['name' => 'Juárez', 'state_name' => 'Chihuahua', 'country_code' => 'MX'],
            ['name' => 'Zapopan', 'state_name' => 'Jalisco', 'country_code' => 'MX'],
            ['name' => 'Monterrey', 'state_name' => 'Nuevo León', 'country_code' => 'MX'],
            ['name' => 'Mérida', 'state_name' => 'Yucatán', 'country_code' => 'MX'],
            ['name' => 'Chihuahua', 'state_name' => 'Chihuahua', 'country_code' => 'MX'],
            ['name' => 'Toluca', 'state_name' => 'State of Mexico', 'country_code' => 'MX'],
            ['name' => 'Cancún', 'state_name' => 'Quintana Roo', 'country_code' => 'MX'],
            ['name' => 'Saltillo', 'state_name' => 'Coahuila', 'country_code' => 'MX'],
            ['name' => 'Aguascalientes', 'state_name' => 'Aguascalientes', 'country_code' => 'MX'],
            ['name' => 'Hermosillo', 'state_name' => 'Sonora', 'country_code' => 'MX'],

            ['name' => 'Cairo', 'state_name' => 'Cairo Governorate', 'country_code' => 'EG'],
            ['name' => 'Alexandria', 'state_name' => 'Alexandria Governorate', 'country_code' => 'EG'],
            ['name' => 'Giza', 'state_name' => 'Giza Governorate', 'country_code' => 'EG'],
            ['name' => 'Shubra El Kheima', 'state_name' => 'Qalyubia Governorate', 'country_code' => 'EG'],
            ['name' => 'Port Said', 'state_name' => 'Port Said Governorate', 'country_code' => 'EG'],
            ['name' => 'Suez', 'state_name' => 'Suez Governorate', 'country_code' => 'EG'],
            ['name' => 'Luxor', 'state_name' => 'Luxor Governorate', 'country_code' => 'EG'],
            ['name' => 'al-Mansura', 'state_name' => 'Dakahlia Governorate', 'country_code' => 'EG'],
            ['name' => 'El-Mahalla El-Kubra', 'state_name' => 'Gharbia Governorate', 'country_code' => 'EG'],
            ['name' => 'Tanta', 'state_name' => 'Gharbia Governorate', 'country_code' => 'EG'],
            ['name' => 'Asyut', 'state_name' => 'Asyut Governorate', 'country_code' => 'EG'],
            ['name' => 'Ismailia', 'state_name' => 'Ismailia Governorate', 'country_code' => 'EG'],
            ['name' => 'Faiyum', 'state_name' => 'Faiyum Governorate', 'country_code' => 'EG'],
            ['name' => 'Zagazig', 'state_name' => 'Sharqia Governorate', 'country_code' => 'EG'],
            ['name' => 'Aswan', 'state_name' => 'Aswan Governorate', 'country_code' => 'EG'],

            ['name' => 'Lagos', 'state_name' => 'Lagos', 'country_code' => 'NG'],
            ['name' => 'Kano', 'state_name' => 'Kano', 'country_code' => 'NG'],
            ['name' => 'Ibadan', 'state_name' => 'Oyo', 'country_code' => 'NG'],
            ['name' => 'Kaduna', 'state_name' => 'Kaduna', 'country_code' => 'NG'],
            ['name' => 'Port Harcourt', 'state_name' => 'Rivers', 'country_code' => 'NG'],
            ['name' => 'Benin City', 'state_name' => 'Edo', 'country_code' => 'NG'],
            ['name' => 'Maiduguri', 'state_name' => 'Borno', 'country_code' => 'NG'],
            ['name' => 'Zaria', 'state_name' => 'Kaduna', 'country_code' => 'NG'],
            ['name' => 'Aba', 'state_name' => 'Abia', 'country_code' => 'NG'],
            ['name' => 'Jos', 'state_name' => 'Plateau', 'country_code' => 'NG'],
            ['name' => 'Ilorin', 'state_name' => 'Kwara', 'country_code' => 'NG'],
            ['name' => 'Abuja', 'state_name' => 'Federal Capital Territory', 'country_code' => 'NG'],

            ['name' => 'Nairobi', 'state_name' => 'Nairobi', 'country_code' => 'KE'],
            ['name' => 'Mombasa', 'state_name' => 'Mombasa', 'country_code' => 'KE'],
            ['name' => 'Kisumu', 'state_name' => 'Kisumu', 'country_code' => 'KE'],
            ['name' => 'Nakuru', 'state_name' => 'Nakuru', 'country_code' => 'KE'],
            ['name' => 'Eldoret', 'state_name' => 'Uasin Gishu', 'country_code' => 'KE'],
            ['name' => 'Ruiru', 'state_name' => 'Kiambu', 'country_code' => 'KE'],
            ['name' => 'Kikuyu', 'state_name' => 'Kiambu', 'country_code' => 'KE'],
            ['name' => 'Kangundo-Tala', 'state_name' => 'Machakos', 'country_code' => 'KE'],
            ['name' => 'Malindi', 'state_name' => 'Kilifi', 'country_code' => 'KE'],
            ['name' => 'Naivasha', 'state_name' => 'Nakuru', 'country_code' => 'KE'],

            ['name' => 'Cape Town', 'state_name' => 'Western Cape', 'country_code' => 'ZA'],
            ['name' => 'Durban', 'state_name' => 'KwaZulu-Natal', 'country_code' => 'ZA'],
            ['name' => 'Johannesburg', 'state_name' => 'Gauteng', 'country_code' => 'ZA'],
            ['name' => 'Soweto', 'state_name' => 'Gauteng', 'country_code' => 'ZA'],
            ['name' => 'Pretoria', 'state_name' => 'Gauteng', 'country_code' => 'ZA'],
            ['name' => 'Port Elizabeth', 'state_name' => 'Eastern Cape', 'country_code' => 'ZA'],
            ['name' => 'Pietermaritzburg', 'state_name' => 'KwaZulu-Natal', 'country_code' => 'ZA'],
            ['name' => 'Benoni', 'state_name' => 'Gauteng', 'country_code' => 'ZA'],
            ['name' => 'Vereeniging', 'state_name' => 'Gauteng', 'country_code' => 'ZA'],
            ['name' => 'Bloemfontein', 'state_name' => 'Free State', 'country_code' => 'ZA'],

            ['name' => 'Moscow', 'state_name' => 'Moscow', 'country_code' => 'RU'],
            ['name' => 'Saint Petersburg', 'state_name' => 'Saint Petersburg', 'country_code' => 'RU'],
            ['name' => 'Novosibirsk', 'state_name' => 'Novosibirsk Oblast', 'country_code' => 'RU'],
            ['name' => 'Yekaterinburg', 'state_name' => 'Sverdlovsk Oblast', 'country_code' => 'RU'],
            ['name' => 'Nizhny Novgorod', 'state_name' => 'Nizhny Novgorod Oblast', 'country_code' => 'RU'],
            ['name' => 'Kazan', 'state_name' => 'Tatarstan', 'country_code' => 'RU'],
            ['name' => 'Chelyabinsk', 'state_name' => 'Chelyabinsk Oblast', 'country_code' => 'RU'],
            ['name' => 'Samara', 'state_name' => 'Samara Oblast', 'country_code' => 'RU'],
            ['name' => 'Omsk', 'state_name' => 'Omsk Oblast', 'country_code' => 'RU'],
            ['name' => 'Rostov-on-Don', 'state_name' => 'Rostov Oblast', 'country_code' => 'RU'],
            ['name' => 'Ufa', 'state_name' => 'Bashkortostan', 'country_code' => 'RU'],
            ['name' => 'Krasnoyarsk', 'state_name' => 'Krasnoyarsk Krai', 'country_code' => 'RU'],
            ['name' => 'Perm', 'state_name' => 'Perm Krai', 'country_code' => 'RU'],
            ['name' => 'Voronezh', 'state_name' => 'Voronezh Oblast', 'country_code' => 'RU'],
            ['name' => 'Volgograd', 'state_name' => 'Volgograd Oblast', 'country_code' => 'RU'],

            ['name' => 'Buenos Aires', 'state_name' => 'Buenos Aires', 'country_code' => 'AR'],
            ['name' => 'Córdoba', 'state_name' => 'Córdoba', 'country_code' => 'AR'],
            ['name' => 'Rosario', 'state_name' => 'Santa Fe', 'country_code' => 'AR'],
            ['name' => 'Mendoza', 'state_name' => 'Mendoza', 'country_code' => 'AR'],
            ['name' => 'La Plata', 'state_name' => 'Buenos Aires', 'country_code' => 'AR'],
            ['name' => 'Mar del Plata', 'state_name' => 'Buenos Aires', 'country_code' => 'AR'],
            ['name' => 'Salta', 'state_name' => 'Salta', 'country_code' => 'AR'],
            ['name' => 'Santa Fe', 'state_name' => 'Santa Fe', 'country_code' => 'AR'],
            ['name' => 'San Juan', 'state_name' => 'San Juan', 'country_code' => 'AR'],

            ['name' => 'New Zealand', 'state_name' => 'Auckland', 'country_code' => 'NZ', 'city_name' => 'Auckland'],
            ['name' => 'Wellington', 'state_name' => 'Wellington', 'country_code' => 'NZ'],
            ['name' => 'Christchurch', 'state_name' => 'Canterbury', 'country_code' => 'NZ'],
            ['name' => 'Manukau', 'state_name' => 'Auckland', 'country_code' => 'NZ'],
            ['name' => 'Waitakere', 'state_name' => 'Auckland', 'country_code' => 'NZ'],
            ['name' => 'North Shore', 'state_name' => 'Auckland', 'country_code' => 'NZ'],
            ['name' => 'Hamilton', 'state_name' => 'Waikato', 'country_code' => 'NZ'],
            ['name' => 'Dunedin', 'state_name' => 'Otago', 'country_code' => 'NZ'],
            ['name' => 'Tauranga', 'state_name' => 'Bay of Plenty', 'country_code' => 'NZ'],
            ['name' => 'Lower Hutt', 'state_name' => 'Wellington', 'country_code' => 'NZ'],

            ['name' => 'Singapore', 'state_name' => 'Central Region', 'country_code' => 'SG'],
        ];

        foreach ($cities as $cityData) {
            // Handle special case for Auckland, NZ
            $cityName = isset($cityData['city_name']) ? $cityData['city_name'] : $cityData['name'];
            
            $country = Country::where('code', $cityData['country_code'])->first();
            if ($country) {
                $state = State::where('name', $cityData['state_name'])
                    ->where('country_id', $country->id)
                    ->first();
                
                if ($state) {
                    City::create([
                        'name' => $cityName,
                        'state_id' => $state->id,
                        'country_id' => $country->id,
                    ]);
                }
            }
        }
    }
}
