<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Country;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            ['name' => 'India', 'code' => 'IN', 'iso3' => 'IND', 'phone_code' => '+91', 'currency' => 'INR', 'currency_symbol' => '₹', 'capital' => 'New Delhi', 'region' => 'Asia', 'subregion' => 'Southern Asia', 'latitude' => '20.593684', 'longitude' => '78.96288'],
            ['name' => 'United States', 'code' => 'US', 'iso3' => 'USA', 'phone_code' => '+1', 'currency' => 'USD', 'currency_symbol' => '$', 'capital' => 'Washington, D.C.', 'region' => 'Americas', 'subregion' => 'Northern America', 'latitude' => '37.09024', 'longitude' => '-95.712891'],
            ['name' => 'United Kingdom', 'code' => 'GB', 'iso3' => 'GBR', 'phone_code' => '+44', 'currency' => 'GBP', 'currency_symbol' => '£', 'capital' => 'London', 'region' => 'Europe', 'subregion' => 'Northern Europe', 'latitude' => '55.378051', 'longitude' => '-3.435973'],
            ['name' => 'Canada', 'code' => 'CA', 'iso3' => 'CAN', 'phone_code' => '+1', 'currency' => 'CAD', 'currency_symbol' => 'CA$', 'capital' => 'Ottawa', 'region' => 'Americas', 'subregion' => 'Northern America', 'latitude' => '56.130366', 'longitude' => '-106.346771'],
            ['name' => 'Australia', 'code' => 'AU', 'iso3' => 'AUS', 'phone_code' => '+61', 'currency' => 'AUD', 'currency_symbol' => 'A$', 'capital' => 'Canberra', 'region' => 'Oceania', 'subregion' => 'Australia and New Zealand', 'latitude' => '-25.274398', 'longitude' => '133.775136'],
            ['name' => 'Germany', 'code' => 'DE', 'iso3' => 'DEU', 'phone_code' => '+49', 'currency' => 'EUR', 'currency_symbol' => '€', 'capital' => 'Berlin', 'region' => 'Europe', 'subregion' => 'Western Europe', 'latitude' => '51.165691', 'longitude' => '10.451526'],
            ['name' => 'France', 'code' => 'FR', 'iso3' => 'FRA', 'phone_code' => '+33', 'currency' => 'EUR', 'currency_symbol' => '€', 'capital' => 'Paris', 'region' => 'Europe', 'subregion' => 'Western Europe', 'latitude' => '46.227638', 'longitude' => '2.213749'],
            ['name' => 'China', 'code' => 'CN', 'iso3' => 'CHN', 'phone_code' => '+86', 'currency' => 'CNY', 'currency_symbol' => '¥', 'capital' => 'Beijing', 'region' => 'Asia', 'subregion' => 'Eastern Asia', 'latitude' => '35.86166', 'longitude' => '104.195397'],
            ['name' => 'Japan', 'code' => 'JP', 'iso3' => 'JPN', 'phone_code' => '+81', 'currency' => 'JPY', 'currency_symbol' => '¥', 'capital' => 'Tokyo', 'region' => 'Asia', 'subregion' => 'Eastern Asia', 'latitude' => '36.204824', 'longitude' => '138.252924'],
            ['name' => 'Brazil', 'code' => 'BR', 'iso3' => 'BRA', 'phone_code' => '+55', 'currency' => 'BRL', 'currency_symbol' => 'R$', 'capital' => 'Brasília', 'region' => 'Americas', 'subregion' => 'South America', 'latitude' => '-14.235004', 'longitude' => '-51.92528'],
            ['name' => 'Russia', 'code' => 'RU', 'iso3' => 'RUS', 'phone_code' => '+7', 'currency' => 'RUB', 'currency_symbol' => '₽', 'capital' => 'Moscow', 'region' => 'Europe', 'subregion' => 'Eastern Europe', 'latitude' => '61.52401', 'longitude' => '105.318756'],
            ['name' => 'South Africa', 'code' => 'ZA', 'iso3' => 'ZAF', 'phone_code' => '+27', 'currency' => 'ZAR', 'currency_symbol' => 'R', 'capital' => 'Pretoria', 'region' => 'Africa', 'subregion' => 'Southern Africa', 'latitude' => '-30.559482', 'longitude' => '22.937506'],
            ['name' => 'Mexico', 'code' => 'MX', 'iso3' => 'MEX', 'phone_code' => '+52', 'currency' => 'MXN', 'currency_symbol' => 'Mex$', 'capital' => 'Mexico City', 'region' => 'Americas', 'subregion' => 'Central America', 'latitude' => '23.634501', 'longitude' => '-102.552784'],
            ['name' => 'Italy', 'code' => 'IT', 'iso3' => 'ITA', 'phone_code' => '+39', 'currency' => 'EUR', 'currency_symbol' => '€', 'capital' => 'Rome', 'region' => 'Europe', 'subregion' => 'Southern Europe', 'latitude' => '41.87194', 'longitude' => '12.56738'],
            ['name' => 'Spain', 'code' => 'ES', 'iso3' => 'ESP', 'phone_code' => '+34', 'currency' => 'EUR', 'currency_symbol' => '€', 'capital' => 'Madrid', 'region' => 'Europe', 'subregion' => 'Southern Europe', 'latitude' => '40.463667', 'longitude' => '-3.74922'],
            ['name' => 'Argentina', 'code' => 'AR', 'iso3' => 'ARG', 'phone_code' => '+54', 'currency' => 'ARS', 'currency_symbol' => '$', 'capital' => 'Buenos Aires', 'region' => 'Americas', 'subregion' => 'South America', 'latitude' => '-38.416097', 'longitude' => '-63.616672'],
            ['name' => 'Netherlands', 'code' => 'NL', 'iso3' => 'NLD', 'phone_code' => '+31', 'currency' => 'EUR', 'currency_symbol' => '€', 'capital' => 'Amsterdam', 'region' => 'Europe', 'subregion' => 'Western Europe', 'latitude' => '52.132633', 'longitude' => '5.291266'],
            ['name' => 'Switzerland', 'code' => 'CH', 'iso3' => 'CHE', 'phone_code' => '+41', 'currency' => 'CHF', 'currency_symbol' => 'Fr', 'capital' => 'Bern', 'region' => 'Europe', 'subregion' => 'Western Europe', 'latitude' => '46.818188', 'longitude' => '8.227512'],
            ['name' => 'Singapore', 'code' => 'SG', 'iso3' => 'SGP', 'phone_code' => '+65', 'currency' => 'SGD', 'currency_symbol' => 'S$', 'capital' => 'Singapore', 'region' => 'Asia', 'subregion' => 'South-Eastern Asia', 'latitude' => '1.352083', 'longitude' => '103.819836'],
            ['name' => 'United Arab Emirates', 'code' => 'AE', 'iso3' => 'ARE', 'phone_code' => '+971', 'currency' => 'AED', 'currency_symbol' => 'د.إ', 'capital' => 'Abu Dhabi', 'region' => 'Asia', 'subregion' => 'Western Asia', 'latitude' => '23.424076', 'longitude' => '53.847818'],
            ['name' => 'Pakistan', 'code' => 'PK', 'iso3' => 'PAK', 'phone_code' => '+92', 'currency' => 'PKR', 'currency_symbol' => '₨', 'capital' => 'Islamabad', 'region' => 'Asia', 'subregion' => 'Southern Asia', 'latitude' => '30.375321', 'longitude' => '69.345116'],
            ['name' => 'Bangladesh', 'code' => 'BD', 'iso3' => 'BGD', 'phone_code' => '+880', 'currency' => 'BDT', 'currency_symbol' => '৳', 'capital' => 'Dhaka', 'region' => 'Asia', 'subregion' => 'Southern Asia', 'latitude' => '23.684994', 'longitude' => '90.356331'],
            ['name' => 'Sri Lanka', 'code' => 'LK', 'iso3' => 'LKA', 'phone_code' => '+94', 'currency' => 'LKR', 'currency_symbol' => 'Rs', 'capital' => 'Colombo', 'region' => 'Asia', 'subregion' => 'Southern Asia', 'latitude' => '7.873054', 'longitude' => '80.771797'],
            ['name' => 'Nepal', 'code' => 'NP', 'iso3' => 'NPL', 'phone_code' => '+977', 'currency' => 'NPR', 'currency_symbol' => 'Rs', 'capital' => 'Kathmandu', 'region' => 'Asia', 'subregion' => 'Southern Asia', 'latitude' => '28.394857', 'longitude' => '84.124008'],
            ['name' => 'Malaysia', 'code' => 'MY', 'iso3' => 'MYS', 'phone_code' => '+60', 'currency' => 'MYR', 'currency_symbol' => 'RM', 'capital' => 'Kuala Lumpur', 'region' => 'Asia', 'subregion' => 'South-Eastern Asia', 'latitude' => '4.210484', 'longitude' => '101.975766'],
            ['name' => 'Indonesia', 'code' => 'ID', 'iso3' => 'IDN', 'phone_code' => '+62', 'currency' => 'IDR', 'currency_symbol' => 'Rp', 'capital' => 'Jakarta', 'region' => 'Asia', 'subregion' => 'South-Eastern Asia', 'latitude' => '-0.789275', 'longitude' => '113.921327'],
            ['name' => 'Thailand', 'code' => 'TH', 'iso3' => 'THA', 'phone_code' => '+66', 'currency' => 'THB', 'currency_symbol' => '฿', 'capital' => 'Bangkok', 'region' => 'Asia', 'subregion' => 'South-Eastern Asia', 'latitude' => '15.870032', 'longitude' => '100.992541'],
            ['name' => 'Philippines', 'code' => 'PH', 'iso3' => 'PHL', 'phone_code' => '+63', 'currency' => 'PHP', 'currency_symbol' => '₱', 'capital' => 'Manila', 'region' => 'Asia', 'subregion' => 'South-Eastern Asia', 'latitude' => '12.879721', 'longitude' => '121.774017'],
            ['name' => 'Vietnam', 'code' => 'VN', 'iso3' => 'VNM', 'phone_code' => '+84', 'currency' => 'VND', 'currency_symbol' => '₫', 'capital' => 'Hanoi', 'region' => 'Asia', 'subregion' => 'South-Eastern Asia', 'latitude' => '14.058324', 'longitude' => '108.277199'],
            ['name' => 'Saudi Arabia', 'code' => 'SA', 'iso3' => 'SAU', 'phone_code' => '+966', 'currency' => 'SAR', 'currency_symbol' => '﷼', 'capital' => 'Riyadh', 'region' => 'Asia', 'subregion' => 'Western Asia', 'latitude' => '23.885942', 'longitude' => '45.079162'],
            ['name' => 'Turkey', 'code' => 'TR', 'iso3' => 'TUR', 'phone_code' => '+90', 'currency' => 'TRY', 'currency_symbol' => '₺', 'capital' => 'Ankara', 'region' => 'Asia', 'subregion' => 'Western Asia', 'latitude' => '38.963745', 'longitude' => '35.243322'],
            ['name' => 'South Korea', 'code' => 'KR', 'iso3' => 'KOR', 'phone_code' => '+82', 'currency' => 'KRW', 'currency_symbol' => '₩', 'capital' => 'Seoul', 'region' => 'Asia', 'subregion' => 'Eastern Asia', 'latitude' => '35.907757', 'longitude' => '127.766922'],
            ['name' => 'New Zealand', 'code' => 'NZ', 'iso3' => 'NZL', 'phone_code' => '+64', 'currency' => 'NZD', 'currency_symbol' => 'NZ$', 'capital' => 'Wellington', 'region' => 'Oceania', 'subregion' => 'Australia and New Zealand', 'latitude' => '-40.900557', 'longitude' => '174.885971'],
            ['name' => 'Egypt', 'code' => 'EG', 'iso3' => 'EGY', 'phone_code' => '+20', 'currency' => 'EGP', 'currency_symbol' => '£', 'capital' => 'Cairo', 'region' => 'Africa', 'subregion' => 'Northern Africa', 'latitude' => '26.820553', 'longitude' => '30.802498'],
            ['name' => 'Nigeria', 'code' => 'NG', 'iso3' => 'NGA', 'phone_code' => '+234', 'currency' => 'NGN', 'currency_symbol' => '₦', 'capital' => 'Abuja', 'region' => 'Africa', 'subregion' => 'Western Africa', 'latitude' => '9.081999', 'longitude' => '8.675277'],
            ['name' => 'Kenya', 'code' => 'KE', 'iso3' => 'KEN', 'phone_code' => '+254', 'currency' => 'KES', 'currency_symbol' => 'KSh', 'capital' => 'Nairobi', 'region' => 'Africa', 'subregion' => 'Eastern Africa', 'latitude' => '-0.023559', 'longitude' => '37.906193'],
            ['name' => 'Israel', 'code' => 'IL', 'iso3' => 'ISR', 'phone_code' => '+972', 'currency' => 'ILS', 'currency_symbol' => '₪', 'capital' => 'Jerusalem', 'region' => 'Asia', 'subregion' => 'Western Asia', 'latitude' => '31.046051', 'longitude' => '34.851612'],
            ['name' => 'Iran', 'code' => 'IR', 'iso3' => 'IRN', 'phone_code' => '+98', 'currency' => 'IRR', 'currency_symbol' => '﷼', 'capital' => 'Tehran', 'region' => 'Asia', 'subregion' => 'Southern Asia', 'latitude' => '32.427908', 'longitude' => '53.688046'],
            ['name' => 'Iraq', 'code' => 'IQ', 'iso3' => 'IRQ', 'phone_code' => '+964', 'currency' => 'IQD', 'currency_symbol' => 'ع.د', 'capital' => 'Baghdad', 'region' => 'Asia', 'subregion' => 'Western Asia', 'latitude' => '33.223191', 'longitude' => '43.679291'],
            ['name' => 'Afghanistan', 'code' => 'AF', 'iso3' => 'AFG', 'phone_code' => '+93', 'currency' => 'AFN', 'currency_symbol' => '؋', 'capital' => 'Kabul', 'region' => 'Asia', 'subregion' => 'Southern Asia', 'latitude' => '33.93911', 'longitude' => '67.709953'],
            ['name' => 'Myanmar', 'code' => 'MM', 'iso3' => 'MMR', 'phone_code' => '+95', 'currency' => 'MMK', 'currency_symbol' => 'K', 'capital' => 'Naypyidaw', 'region' => 'Asia', 'subregion' => 'South-Eastern Asia', 'latitude' => '21.913965', 'longitude' => '95.956223'],
            ['name' => 'Chile', 'code' => 'CL', 'iso3' => 'CHL', 'phone_code' => '+56', 'currency' => 'CLP', 'currency_symbol' => '$', 'capital' => 'Santiago', 'region' => 'Americas', 'subregion' => 'South America', 'latitude' => '-35.675147', 'longitude' => '-71.542969'],
            ['name' => 'Colombia', 'code' => 'CO', 'iso3' => 'COL', 'phone_code' => '+57', 'currency' => 'COP', 'currency_symbol' => '$', 'capital' => 'Bogotá', 'region' => 'Americas', 'subregion' => 'South America', 'latitude' => '4.570868', 'longitude' => '-74.297333'],
            ['name' => 'Peru', 'code' => 'PE', 'iso3' => 'PER', 'phone_code' => '+51', 'currency' => 'PEN', 'currency_symbol' => 'S/', 'capital' => 'Lima', 'region' => 'Americas', 'subregion' => 'South America', 'latitude' => '-9.189967', 'longitude' => '-75.015152'],
            ['name' => 'Venezuela', 'code' => 'VE', 'iso3' => 'VEN', 'phone_code' => '+58', 'currency' => 'VES', 'currency_symbol' => 'Bs.S.', 'capital' => 'Caracas', 'region' => 'Americas', 'subregion' => 'South America', 'latitude' => '6.42375', 'longitude' => '-66.58973'],
            ['name' => 'Sweden', 'code' => 'SE', 'iso3' => 'SWE', 'phone_code' => '+46', 'currency' => 'SEK', 'currency_symbol' => 'kr', 'capital' => 'Stockholm', 'region' => 'Europe', 'subregion' => 'Northern Europe', 'latitude' => '60.128161', 'longitude' => '18.643501'],
            ['name' => 'Norway', 'code' => 'NO', 'iso3' => 'NOR', 'phone_code' => '+47', 'currency' => 'NOK', 'currency_symbol' => 'kr', 'capital' => 'Oslo', 'region' => 'Europe', 'subregion' => 'Northern Europe', 'latitude' => '60.472024', 'longitude' => '8.468946'],
            ['name' => 'Denmark', 'code' => 'DK', 'iso3' => 'DNK', 'phone_code' => '+45', 'currency' => 'DKK', 'currency_symbol' => 'kr', 'capital' => 'Copenhagen', 'region' => 'Europe', 'subregion' => 'Northern Europe', 'latitude' => '56.26392', 'longitude' => '9.501785'],
            ['name' => 'Poland', 'code' => 'PL', 'iso3' => 'POL', 'phone_code' => '+48', 'currency' => 'PLN', 'currency_symbol' => 'zł', 'capital' => 'Warsaw', 'region' => 'Europe', 'subregion' => 'Eastern Europe', 'latitude' => '51.919438', 'longitude' => '19.145136'],
            ['name' => 'Ukraine', 'code' => 'UA', 'iso3' => 'UKR', 'phone_code' => '+380', 'currency' => 'UAH', 'currency_symbol' => '₴', 'capital' => 'Kyiv', 'region' => 'Europe', 'subregion' => 'Eastern Europe', 'latitude' => '48.379433', 'longitude' => '31.16558'],
            ['name' => 'Portugal', 'code' => 'PT', 'iso3' => 'PRT', 'phone_code' => '+351', 'currency' => 'EUR', 'currency_symbol' => '€', 'capital' => 'Lisbon', 'region' => 'Europe', 'subregion' => 'Southern Europe', 'latitude' => '39.399872', 'longitude' => '-8.224454'],
            ['name' => 'Greece', 'code' => 'GR', 'iso3' => 'GRC', 'phone_code' => '+30', 'currency' => 'EUR', 'currency_symbol' => '€', 'capital' => 'Athens', 'region' => 'Europe', 'subregion' => 'Southern Europe', 'latitude' => '39.074208', 'longitude' => '21.824312'],
            ['name' => 'Czech Republic', 'code' => 'CZ', 'iso3' => 'CZE', 'phone_code' => '+420', 'currency' => 'CZK', 'currency_symbol' => 'Kč', 'capital' => 'Prague', 'region' => 'Europe', 'subregion' => 'Eastern Europe', 'latitude' => '49.817492', 'longitude' => '15.472962'],
            ['name' => 'Hungary', 'code' => 'HU', 'iso3' => 'HUN', 'phone_code' => '+36', 'currency' => 'HUF', 'currency_symbol' => 'Ft', 'capital' => 'Budapest', 'region' => 'Europe', 'subregion' => 'Eastern Europe', 'latitude' => '47.162494', 'longitude' => '19.503304'],
            ['name' => 'Austria', 'code' => 'AT', 'iso3' => 'AUT', 'phone_code' => '+43', 'currency' => 'EUR', 'currency_symbol' => '€', 'capital' => 'Vienna', 'region' => 'Europe', 'subregion' => 'Western Europe', 'latitude' => '47.516231', 'longitude' => '14.550072'],
            ['name' => 'Belgium', 'code' => 'BE', 'iso3' => 'BEL', 'phone_code' => '+32', 'currency' => 'EUR', 'currency_symbol' => '€', 'capital' => 'Brussels', 'region' => 'Europe', 'subregion' => 'Western Europe', 'latitude' => '50.503887', 'longitude' => '4.469936'],
            ['name' => 'Finland', 'code' => 'FI', 'iso3' => 'FIN', 'phone_code' => '+358', 'currency' => 'EUR', 'currency_symbol' => '€', 'capital' => 'Helsinki', 'region' => 'Europe', 'subregion' => 'Northern Europe', 'latitude' => '61.92411', 'longitude' => '25.748151'],
            ['name' => 'Ireland', 'code' => 'IE', 'iso3' => 'IRL', 'phone_code' => '+353', 'currency' => 'EUR', 'currency_symbol' => '€', 'capital' => 'Dublin', 'region' => 'Europe', 'subregion' => 'Northern Europe', 'latitude' => '53.41291', 'longitude' => '-8.24389'],
            ['name' => 'Qatar', 'code' => 'QA', 'iso3' => 'QAT', 'phone_code' => '+974', 'currency' => 'QAR', 'currency_symbol' => '﷼', 'capital' => 'Doha', 'region' => 'Asia', 'subregion' => 'Western Asia', 'latitude' => '25.354826', 'longitude' => '51.183884'],
            ['name' => 'Kuwait', 'code' => 'KW', 'iso3' => 'KWT', 'phone_code' => '+965', 'currency' => 'KWD', 'currency_symbol' => 'د.ك', 'capital' => 'Kuwait City', 'region' => 'Asia', 'subregion' => 'Western Asia', 'latitude' => '29.31166', 'longitude' => '47.481766'],
            ['name' => 'Oman', 'code' => 'OM', 'iso3' => 'OMN', 'phone_code' => '+968', 'currency' => 'OMR', 'currency_symbol' => '﷼', 'capital' => 'Muscat', 'region' => 'Asia', 'subregion' => 'Western Asia', 'latitude' => '21.512583', 'longitude' => '55.923255'],
            ['name' => 'Bahrain', 'code' => 'BH', 'iso3' => 'BHR', 'phone_code' => '+973', 'currency' => 'BHD', 'currency_symbol' => '.د.ب', 'capital' => 'Manama', 'region' => 'Asia', 'subregion' => 'Western Asia', 'latitude' => '25.930414', 'longitude' => '50.637772'],
            ['name' => 'Jordan', 'code' => 'JO', 'iso3' => 'JOR', 'phone_code' => '+962', 'currency' => 'JOD', 'currency_symbol' => 'د.ا', 'capital' => 'Amman', 'region' => 'Asia', 'subregion' => 'Western Asia', 'latitude' => '30.585164', 'longitude' => '36.238414'],
            ['name' => 'Lebanon', 'code' => 'LB', 'iso3' => 'LBN', 'phone_code' => '+961', 'currency' => 'LBP', 'currency_symbol' => '£', 'capital' => 'Beirut', 'region' => 'Asia', 'subregion' => 'Western Asia', 'latitude' => '33.854721', 'longitude' => '35.862285'],
            ['name' => 'Morocco', 'code' => 'MA', 'iso3' => 'MAR', 'phone_code' => '+212', 'currency' => 'MAD', 'currency_symbol' => 'د.م.', 'capital' => 'Rabat', 'region' => 'Africa', 'subregion' => 'Northern Africa', 'latitude' => '31.791702', 'longitude' => '-7.09262'],
            ['name' => 'Algeria', 'code' => 'DZ', 'iso3' => 'DZA', 'phone_code' => '+213', 'currency' => 'DZD', 'currency_symbol' => 'د.ج', 'capital' => 'Algiers', 'region' => 'Africa', 'subregion' => 'Northern Africa', 'latitude' => '28.033886', 'longitude' => '1.659626'],
            ['name' => 'Tunisia', 'code' => 'TN', 'iso3' => 'TUN', 'phone_code' => '+216', 'currency' => 'TND', 'currency_symbol' => 'د.ت', 'capital' => 'Tunis', 'region' => 'Africa', 'subregion' => 'Northern Africa', 'latitude' => '33.886917', 'longitude' => '9.537499'],
            ['name' => 'Ethiopia', 'code' => 'ET', 'iso3' => 'ETH', 'phone_code' => '+251', 'currency' => 'ETB', 'currency_symbol' => 'Br', 'capital' => 'Addis Ababa', 'region' => 'Africa', 'subregion' => 'Eastern Africa', 'latitude' => '9.145', 'longitude' => '40.489673'],
            ['name' => 'Ghana', 'code' => 'GH', 'iso3' => 'GHA', 'phone_code' => '+233', 'currency' => 'GHS', 'currency_symbol' => '₵', 'capital' => 'Accra', 'region' => 'Africa', 'subregion' => 'Western Africa', 'latitude' => '7.946527', 'longitude' => '-1.023194'],
            ['name' => 'Tanzania', 'code' => 'TZ', 'iso3' => 'TZA', 'phone_code' => '+255', 'currency' => 'TZS', 'currency_symbol' => 'Sh', 'capital' => 'Dodoma', 'region' => 'Africa', 'subregion' => 'Eastern Africa', 'latitude' => '-6.369028', 'longitude' => '34.888822'],
            ['name' => 'Uganda', 'code' => 'UG', 'iso3' => 'UGA', 'phone_code' => '+256', 'currency' => 'UGX', 'currency_symbol' => 'Sh', 'capital' => 'Kampala', 'region' => 'Africa', 'subregion' => 'Eastern Africa', 'latitude' => '1.373333', 'longitude' => '32.290275'],
            ['name' => 'Zimbabwe', 'code' => 'ZW', 'iso3' => 'ZWE', 'phone_code' => '+263', 'currency' => 'ZWL', 'currency_symbol' => '$', 'capital' => 'Harare', 'region' => 'Africa', 'subregion' => 'Eastern Africa', 'latitude' => '-19.015438', 'longitude' => '29.154857'],
            ['name' => 'Zambia', 'code' => 'ZM', 'iso3' => 'ZMB', 'phone_code' => '+260', 'currency' => 'ZMW', 'currency_symbol' => 'ZK', 'capital' => 'Lusaka', 'region' => 'Africa', 'subregion' => 'Eastern Africa', 'latitude' => '-13.133897', 'longitude' => '27.849332'],
        ];

        foreach ($countries as $country) {
            Country::create($country);
        }
    }
}
